name: Auto-Create GitHub Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get tag info
        id: tag_info
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

          # Check if this is a development release (contains -dev.)
          if [[ "$TAG_NAME" == *"-dev."* ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
            echo "release_title=$TAG_NAME (Development Release)" >> $GITHUB_OUTPUT
            echo "release_body=🚧 **Development Release** - This is a pre-release version for testing purposes. Use with caution in production environments." >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
            echo "release_title=$TAG_NAME" >> $GITHUB_OUTPUT
            echo "release_body=🎉 **Stable Release** - This release has been tested and is ready for production use." >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_info.outputs.tag_name }}
          name: ${{ steps.tag_info.outputs.release_title }}
          body: |
            ${{ steps.tag_info.outputs.release_body }}

            ## 📦 Installation

            ```bash
            npm install @orc-hfg/madek-api-nuxt-layer@${{ steps.tag_info.outputs.tag_name }}
            ```

            ## 🔄 Automatic Publishing

            This release will be automatically published to GitHub Packages.

            ---

            *This release was created automatically by GitHub Actions.*
          draft: false
          prerelease: ${{ steps.tag_info.outputs.is_prerelease == 'true' }}
          generate_release_notes: true
