# Quality assurance workflow
#
# This workflow ensures code quality and package integrity for the madek-api-nuxt-layer.
# It runs comprehensive checks on every push to main and pull requests to catch issues early.
#
# Design decisions:
# 1. **Job-gate pattern**: Release commit detection runs as separate job with output,
#    eliminating the need for conditional checks on every individual step.
#
# 2. **Workflow coordination**: Works in tandem with the release workflow:
#    - This workflow: Handles regular development (pushes to main, PRs)
#    - Release workflow: Handles releases (version tags) and includes quality assurance steps
#    - Release commit detection prevents overlap and resource waste
#
# 3. **Performance optimizations**: Uses integrated Node.js setup caching and optimized
#    npm flags (--no-audit --no-fund --loglevel=error) for faster CI builds and reduced noise in logs.
#
# 4. **Package verification**: Ensures the package can be properly packed with npm pack,
#    verifying package integrity before any potential release.

name: Quality assurance

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Prevent parallel CI runs for the same PR to save resources
# and avoid conflicts during testing
concurrency:
  group: layer-qa-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-release-commit:
    name: Detect release commit
    uses: ./.github/workflows/detect-release-commit.yml

  quality-assurance:
    name: Quality assurance
    needs: detect-release-commit
    if: needs.detect-release-commit.outputs.is_release_commit == 'false'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node and install dependencies
        uses: ./.github/actions/setup-node-dependencies

      - name: Prepare Nuxt environment
        run: npm run dev:prepare

      - name: Run quality assurance
        uses: ./.github/actions/quality-assurance

      - name: Build application
        run: npm run build

      - name: Verify package can be packed
        run: |
          npm pack --dry-run
          echo "Package packing verification passed"
